Make debile-slave depend on python-yaml
Otherwise, running `debile-slave` crashes with:

Traceback (most recent call last):
  File "/usr/bin/debile-slave", line 9, in <module>
    load_entry_point('debile.slave==0.1', 'console_scripts', 'debile-slave')()
  File "/usr/lib/python2.7/dist-packages/debile/slave/cli.py", line 6, in daemon
    from debile.slave.daemon import main
  File "/usr/lib/python2.7/dist-packages/debile/slave/daemon.py", line 23, in <module>
    from debile.slave.client import get_proxy
  File "/usr/lib/python2.7/dist-packages/debile/slave/client.py", line 22, in <module>
    from debile.slave.utils import tdir, cd, dget, run_command
  File "/usr/lib/python2.7/dist-packages/debile/slave/utils.py", line 23, in <module>
    from debile.slave.core import config
  File "/usr/lib/python2.7/dist-packages/debile/slave/core.py", line 1, in <module>
    from debile.utils.config import load_slave_config
  File "/usr/lib/python2.7/dist-packages/debile/utils/config.py", line 1, in <module>
    import yaml
ImportError: No module named yaml